name: Publish

on:
  release:
    types: [ created ]

jobs:
  npm:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout Code
      - uses: actions/setup-node@v1
        name: Setup Node for NPM
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
        name: Install dependencies
      - run: npm publish
        name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v1
        name: Setup Node for the GitHub Package Registry
        with:
          registry-url: https://npm.pkg.github.com
      - run: npm publish
        name: Publish to the GitHub Package Registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}